# Lab 3
Ali Tejani, amt3639

Caroline Yao, chy253

In [2]:
import numpy as np
import pandas as pd

## Problem 1: Linear Algebra in Python

### 1. 

In [31]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([0, 1, 0, 1])
v3 = np.array([1, 4, 3, 6])
v4 = np.array([2, 11, 6, 15])
subspace = np.column_stack((v1,v2,v3,v4))
print "Subspace rank is {}".format(np.linalg.matrix_rank(subspace))

Subspace rank is 2


In [35]:
vInS = np.array([1, 1, 3, 3])
vNotInS = np.array([1, 1, 0, 0])
s1 = np.concatenate((subspace,np.array([vInS]).T), axis=1)
s2 = np.concatenate((subspace,np.array([vNotInS]).T), axis=1)
print np.linalg.matrix_rank(s1)
print np.linalg.matrix_rank(s2)
print "{} is {}in Span(v1,v2,v3,v4)".format(vInS,'' if np.linalg.matrix_rank(s1) == 2 else 'not ')
print "{} is {}in Span(v1,v2,v3,v4)".format(vNotInS,'' if np.linalg.matrix_rank(s2) == 2 else 'not ')

2
3
[1 1 3 3] is in Span(v1,v2,v3,v4)
[1 1 0 0] is not in Span(v1,v2,v3,v4)


### 2.

In [37]:
print "Subspace dimension is {}".format(np.linalg.matrix_rank(subspace))

Subspace rank is 2


### 3.

In [57]:
subspace = np.column_stack((v1,v2))
q,r = np.linalg.qr(subspace)
e1 = q.T[0]
e2 = q.T[1]
print "Orthonormal basis of S is\n ({}, \n{})".format(e1,e2)


Orthonormal basis of S is
 ([-0.18257419 -0.36514837 -0.54772256 -0.73029674], 
[ 0.2236068  -0.67082039  0.67082039 -0.2236068 ])


### 4.

In [67]:
z = np.array([1,0,0,0])
zProje1 = np.dot(z,e1)*e1
zProje2 = np.dot(z,e2)*e2
zProjS = zProje1 + zProje2
zProjS
s1 = np.concatenate((subspace,np.array([zProjS]).T), axis=1)
print "{} is the closest vector in S to z*".format(zProjS,'' if np.linalg.matrix_rank(s1) == 2 else 'not ')

[ 0.08333333 -0.08333333  0.25        0.08333333] is the closest vector in S to z*


## Problem 2: Scraping, Entropy and ICML papers

ImportError: No module named selenium